---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml
    - ansible/config.yml

  tasks:
    - import_tasks: ansible/update.yml
    - import_tasks: ansible/base_packages.yml
    - import_tasks: ansible/update_grub.yml
    - import_tasks: ansible/swap.yml
      tags: swap
    - import_tasks: ansible/fonts.yml
    - import_tasks: ansible/other_packages.yml
    - import_tasks: ansible/dev_packages.yml
    - import_tasks: ansible/docker.yml
    - import_tasks: ansible/flatpak_packages.yml
    - import_tasks: ansible/dotfiles.yml

