---
- name: Setup my local machine
  hosts: all

  vars_files:
    - default.config.yml
    - ansible/config.yml

  tasks:
    - name: Check that either 'work' or 'private' tag is set
      ansible.builtin.assert:
        that:
          - "'work' in ansible_run_tags or 'private' in ansible_run_tags"
          - "'work' not in ansible_run_tags or 'private' not in ansible_run_tags"
        fail_msg: "You need use either tag 'work' or 'private'"
      tags:
        - always
#    - import_tasks: ansible/update.yml
#      tags: always
#    - import_tasks: ansible/update_grub.yml
#      tags: always
#    - import_tasks: ansible/swap.yml
#      tags: swap
    - import_tasks: ansible/install_packages.yml
    - import_tasks: ansible/docker.yml
      tags: always
    - import_tasks: ansible/flatpak_packages.yml
    - import_tasks: ansible/dotfiles.yml
      tags: always

