# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    review: |
        api -XGET search/issues
        -f q='team-review-requested:rewe-digital-ecom/team-pecunia is:pr is:open archived:false -author:app/dependabot -author:@me'
        --template '{{range .items -}}
        {{.number | printf "#%v" | autocolor "green" }} {{.title | autocolor "white"}} ({{timeago .created_at | autocolor "yellow" }})
        → {{.html_url}} {{print "\n\n" -}}
        {{end}}'
    dependabot: |
        api -XGET search/issues
        -f q='team-review-requested:rewe-digital-ecom/team-pecunia is:pr is:open archived:false author:app/dependabot'
        --template '{{range .items -}}
        {{.number | printf "#%v" | autocolor "green" }} {{.title | autocolor "white"}} ({{timeago .created_at | autocolor "yellow" }})
        → {{.html_url}} {{print "\n\n" -}}
        {{end}}'
    mine: |
        !gh search prs \
        --author @me \
        --state open \
        --json url \
        --template '{{range .}}{{.url}}{{print "\n"}}{{end}}' \
        | xargs -r -L 1 gh prstate
    prstate: "pr view\n--json number,title,url,reviewDecision,updatedAt,comments\n--template\n'{{.number | printf \"#%v\" | autocolor \"green\"}} {{.title}} \U0001F5E9 {{len .comments}} ({{timeago .updatedAt | autocolor \"yellow\"}}) {{.reviewDecision}}\n→ {{.url}}{{print \"\\n\\n\"}}'\n"
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
version: "1"
