---
swapfile_path: /swapfile
swapfile_size: 16G

base_packages:
  - base-devel
  - curl
  - git
  - wget
  - yay

font_packages:
  - adobe-source-code-pro-fonts
  - adobe-source-han-sans-otc-fonts # for CJK
  - adobe-source-sans-fonts
  - noto-fonts
  - noto-fonts-emoji # for emoji
  - ttf-dejavu
  - ttf-droid
  - ttf-opensans
  - ttf-roboto
  - ttf-sourcecodepro-nerd
  - ttf-ubuntu-font-family

other_packages:
  - bash-completion
  - bat # cat with line numbers and syntax highlighting
  - btop # alternative to htop
  - evolution # mail client
  - fd # alternative to find
  - firefox
  - flatpak
  - git-delta # show diffs like in git PRs
  - gnome-shell-extension-system-monitor-next-git
  - kitty # GPU powered terminal
  - linux-headers
  - neovim
  - nextcloud-client
  - paru
  - qrencode
  - ripgrep # alternative to grep, command is rg
  - spotify
  - timew
  - tmux
  - vim
  - xclip
  - zsh

dev_packages:
  - docker
  - docker-compose
  - github-client
  - gnu-netcat
#   - intellij-idea-ultimate-edition
  - kcat
  - lazygit
  - python
  - python-pip
  - rustup
  - visual-studio-code-bin

flatpak_packages:
  - com.discordapp.Discord
  - com.google.Chrome
  - org.keepassxc.KeePassXC