---
swapfile_path: /swapfile
swapfile_size: 16G

base_packages:
  - base-devel
  - curl
  - git
  - wget
  - yay

font_packages:
  - adobe-source-code-pro-fonts
  - adobe-source-han-sans-otc-fonts # for CJK
  - adobe-source-sans-fonts
  - noto-fonts
  - noto-fonts-emoji # for emoji
  - ttf-dejavu
  - ttf-droid
  - ttf-opensans
  - ttf-roboto
  - ttf-sourcecodepro-nerd
  - ttf-nerd-fonts-symbols
  - ttf-ubuntu-font-family

other_packages:
  - bash-completion
  - bat # cat with line numbers and syntax highlighting
  - btop # alternative to htop
  - dog # DNS lookup tool
  - evolution # mail client
  - encfs # encrypted directories
  - fd # alternative to find
  - firefox
  - flatpak
  - flatseal # permission manager for flatpak
  - git-delta # show diffs like in git PRs
  - gnome-shell-extension-system-monitor-next-git
  - kitty # GPU powered terminal
  - linux-headers
  - neovim
  - # nextcloud-client # we'll use the flatpak version
  - paru
  - qrencode
  - ripgrep # alternative to grep, command is rg
  - spotify
  - timew
  - tmux
  - tree
  - vim
  - xclip
  - zsh

dev_packages:
  - curlie
  - docker
  - docker-compose
  - google-cloud-cli
  - github-cli
  - openbsd-netcat
  - intellij-idea-ultimate-edition
  - kcat
  - lazygit
  - luarocks
  - podman
  - podman-compose
  - python
  - python-pip
  - tig # terminal ui for git
  - visual-studio-code-bin

flatpak_packages:
  - com.discordapp.Discord
  - com.google.Chrome
  - org.keepassxc.KeePassXC
  - com.slack.Slack
  - com.nextcloud.desktopclient.nextcloud
