---
swapfile_path: /swapfile
swapfile_size: 16G

packages:
  base:
    - base-devel # ubuntu: build-essential
    - curl
    - git
    - wget
    - yay # ubuntu: not needed

  fonts: # see oh-my-zsh/10_fonts.zsh
    - adobe-source-code-pro-fonts # ubuntu: via fnt install google-sourcecodepro
    - adobe-source-han-sans-otc-fonts # for CJK
    - adobe-source-sans-fonts
    - noto-fonts
    - noto-fonts-emoji # for emoji
    - ttf-dejavu
    - ttf-droid
    - ttf-opensans # ubuntu: via fnt install fonts-open-sans
    - ttf-roboto
    - ttf-sourcecodepro-nerd
    - ttf-nerd-fonts-symbols
    - ttf-ubuntu-font-family

  dev:
    - curlie # not using this
    - docker # ubuntu: docker.io
    - docker-compose # ubuntu: docker-compose-v2
    - google-cloud-cli
    - github-cli # ubuntu: gh
    - openbsd-netcat # ubuntu: netcat-openbsd
    - fnt # ubuntu: font download managher
    - jq
    - kcat
    - lazygit # ubuntu: manual install, see https://github.com/jesseduffield/lazygit?tab=readme-ov-file#ubuntu
    - luarocks
    - podman
    - podman-compose
    - python # ubuntu: python3
    - python-pip # ubuntu: python3-pip
    - tig # terminal ui for git
    - visual-studio-code-bin # ubuntu: via snap

  common:
    - bash-completion
    - bat # cat with line numbers and syntax highlighting
    - borg # ubuntu: borgbackup
    - btop # alternative to htop
    - dog # DNS lookup tool, ubuntu: dig
    - evolution # mail client
    - encfs # encrypted directories
    - fd # fast alternative to find, ubuntu: fd-find
    - firefox
    - flatpak # ubuntu uses snap by default
    - flatseal # permission manager for flatpak
    - fzf # command-line fuzzy finder
    - git-delta # show diffs like in git PRs
    - gimp
    - kitty # GPU powered terminal
    - linux-headers
    - neovim
    - # nextcloud-client # we'll use the flatpak version
    - paru
    - qrencode
    - ripgrep # alternative to grep, command is rg
    - spotify
    - shutter # screenshot editor
    - timew
    - tmux
    - tmuxp
    - tree
    - vim
    - xclip
    - zk # zettelkasten tool; ubuntu: manual install https://github.com/zk-org/zk
    - zsh
  work: # packages necessary at work only
    - intellij-idea-ultimate-edition # ubuntu: via snap
    - glab
    - rclone # for gdrive sync
  private: # packages necessary on private computer only
    - digikam
    - qmapshack

flatpak:
  common:
    - com.google.Chrome
    - org.keepassxc.KeePassXC
    - com.slack.Slack
    - com.nextcloud.desktopclient.nextcloud
  work: []
  private:
    - com.discordapp.Discord

