---
- name: Determine where to create the links
  set_fact:
    destination: "{{ lookup('env', 'HOME') }}"

- name: Print where we will execute (defaults to home)
  ansible.builtin.debug:
    msg: "We'll use {{ destination }} as the directory to create everything"

- name: Create necessary directories
  ansible.builtin.file:
    path: "{{ destination }}/{{ item }}"
    state: directory
  loop:
    - .config/gh
    - .config/git
    - .config/ideavim
    - .config/systemd
    - .config/tmux
    - .local/bin

- name: Link dot files and directories
  ansible.builtin.file:
    src: "{{ playbook_dir }}/{{ item }}"
    dest: "{{ destination }}/{{ item }}"
    state: link
    force: true
  loop:
    # dot files in home
    - .bash_logout 
    - .bash_profile 
    - .bashrc 
    - .git-completion.bash 
    - .git-prompt.sh 
    - .gvimrc 
    - .profile 
    - .vim 
    - .zshrc
    # local binaries
    - .local/bin/jcurl
    # configs
    - .config/digikamrc
    - .config/digikam_systemrc
    - .config/gh/config.yml
    - .config/git
    - .config/kitty
    - .config/nvim
    - .config/systemd/user
    - .config/tmux/tmux.conf
    - .config/tmuxp
    - .config/zk
- name: Init submodules
  ansible.builtin.command:
    cmd: "git submodule {{ item }}"
    chdir: "{{ playbook_dir }}"
  loop:
    - init
    - update
