---
- name: Determine where to create the links
  set_fact:
    destination: "{{ lookup('env', 'HOME') }}"

- name: Print where we will execute (defaults to home)
  ansible.builtin.debug:
    msg: "We'll use {{ destination }} as the directory to create everything"

- name: Create necessary directories
  ansible.builtin.file:
    path: "{{ destination }}/.local/bin"
    state: directory

- name: Link dot files and directories
  ansible.builtin.file:
    src: "{{ playbook_dir }}/{{ item }}"
    dest: "{{ destination }}/{{ item }}"
    state: link
    force: true
  loop:
    # dot files in home
    - .bash_logout 
    - .bash_profile 
    - .bashrc 
    - .git-completion.bash 
    - .gitconfig 
    - .git-prompt.sh 
    - .gvimrc 
    - .ideavimrc 
    - .profile 
    - .tmux.conf 
    - .vim 
    - .vimrc
    - .zshrc
    # local binaries
    - .local/bin/jcurl
    # configs
    - .config/digikamrc
    - .config/digikam_systemrc
    - .config/kitty
    - .config/nvim
- name: Init submodules
  ansible.builtin.command:
    cmd: "git submodule {{ item }}"
    chdir: "{{ playbook_dir }}"
  loop:
    - init
    - update
