---
#
# Install software packages
#
- name: Install base packages
  become: true
  community.general.pacman:
    name: "{{ packages.base }}"
    state: present
  changed_when: false
  tags: always

- name: Activate colors in pacman / yay / paru
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#Color'
    line: 'Color'
  tags: always

- name: Install fonts packages
  become: true
  kewlfft.aur.aur:
    name: "{{ packages.fonts }}"
    use: yay
    state: present
  changed_when: false
  tags: always

- name: Install common software
  kewlfft.aur.aur:
    name: "{{ packages.common }}"
    use: yay
    state: present
  tags:
    - work
    - private

- name: Install software for work environment
  kewlfft.aur.aur:
    name: "{{ packages.work }}"
    use: yay
    state: present
  tags: work

- name: Install software for private environment
  kewlfft.aur.aur:
    name: "{{ packages.private }}"
    use: yay
    state: present
  tags: private

- name: Install Dev packages
  kewlfft.aur.aur:
    name: "{{ packages.dev }}"
    use: yay
    state: present
  changed_when: false
  tags: always

