---
#
# Update mirrors and package cache
#
- name: Update mirrors
  become: true
  command: pacman-mirrors --country Germany
  changed_when: false

- name: Update package cache
  become: true
  pacman:
    update_cache: true
  changed_when: false
